Enable Experiment/Scoreset Searches via Associated Publication Identifiers
VariantEffect/mavedb-api pull request #67
Opened 2023-06-07 21:06 UTC by bencap

2023-08-01 18:30 UTC, jstone-uw requested changes

2023-08-01 18:30 UTC, jstone-uw commented on src/mavedb/lib/experiments.py
Is there a reason not to search experiments by exact publication identifier, like we do for score sets?

2023-08-01 18:30 UTC, jstone-uw commented on src/mavedb/routers/publication_identifiers.py
Should any of the publication API endpoints be protected from abuse by requiring the user to be authenticated? It's not a strong protection since anyone can register, but maybe it's worthwhile for any endpoint that isn't used on the search screen.

Also, I'd change the function name fetch_experiment to fetch_publication, even though it doesn't have practical consequences.

2023-08-02 16:38 UTC, bencap commented on src/mavedb/routers/publication_identifiers.py
Yeah that makes sense and I'll go ahead and protect them. I think the idea here is that at some point these endpoints can be used to populate the initial set of filter options at some point instead of fetching all the score-sets. That isn't implemented at the moment, but at that point we could remove the protections.

Thanks for catching the function name, I keep copy pasting routes and making that same mistake...

2023-08-02 17:07 UTC, bencap commented on src/mavedb/lib/experiments.py
Thanks, I thought I had added it but I did not...

2023-08-02 17:28 UTC, bencap commented on src/mavedb/routers/publication_identifiers.py
In light of this I added another fetch route for just identifiers and made those routes raise a `MultipleResultsFound` exception. That exception was previously raised by the search endpoints, which now will just return a list of all matching publications.

2023-08-07 18:07 UTC, merged